# Generated by Django 4.2.27 on 2026-01-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(help_text='Gang tag/abbreviation', max_length=10)),
                ('color', models.CharField(default='#FF0000', help_text='Hex color code', max_length=7)),
                ('territory', models.TextField(blank=True, help_text='Territory description')),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-threat_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GangMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('criminal_record', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('WANTED', 'Wanted'), ('INCARCERATED', 'Incarcerated'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='intelligence.gang')),
                ('known_associates', models.ManyToManyField(blank=True, to='intelligence.gangmember')),
            ],
            options={
                'ordering': ['gang', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('incident_type', models.CharField(choices=[('ASSAULT', 'Assault'), ('ROBBERY', 'Robbery'), ('DRUG_TRAFFICKING', 'Drug Trafficking'), ('MURDER', 'Murder'), ('WEAPONS', 'Weapons Offense'), ('TERRITORY_DISPUTE', 'Territory Dispute'), ('OTHER', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gangs_involved', models.ManyToManyField(blank=True, related_name='incidents', to='intelligence.gang')),
                ('members_involved', models.ManyToManyField(blank=True, related_name='incidents', to='intelligence.gangmember')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active Investigation'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gangs', models.ManyToManyField(blank=True, related_name='cases', to='intelligence.gang')),
                ('lead_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_cases', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='cases', to='intelligence.gangmember')),
                ('team_members', models.ManyToManyField(blank=True, related_name='case_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-opened_date'],
            },
        ),
        migrations.CreateModel(
            name='GangRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('ALLIED', 'Allied'), ('NEUTRAL', 'Neutral'), ('RIVAL', 'Rival'), ('WAR', 'At War')], default='NEUTRAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gang_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_gang1', to='intelligence.gang')),
                ('gang_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_gang2', to='intelligence.gang')),
            ],
            options={
                'unique_together': {('gang_1', 'gang_2')},
            },
        ),
    ]
