# Generated by Django 4.2.27 on 2026-02-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='image',
            field=models.ImageField(blank=True, help_text='Case file image/evidence', null=True, upload_to='case_files/'),
        ),
    ]
